imports:
  - { resource: services.yml }

framework:
    secret: S0ME_SECRET
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false
