imports:
  - { resource: parameters.yml }
  - { resource: services.yml }

framework:
    secret: '%secret%'
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }
    session: ~
    csrf_protection: ~

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/views/admin': admin

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  utf8mb4

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            main:
                is_bundle:  false
                type:       annotation
                dir:        '%kernel.project_dir%/src/Domain'
                prefix:     'PozytywneInicjatywy\Dashboard\Domain'
                alias:      Domain

security:
    encoders:
        PozytywneInicjatywy\Dashboard\Domain\User: bcrypt

    providers:
        entity_provider:
            id: repository.user

    firewalls:
        main:
            pattern: ^/admin
            anonymous: ~

            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin

                username_parameter: username
                password_parameter: password

                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /admin/logout
                target: /admin/login

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/account, roles: IS_AUTHENTICATED_REMEMBERED }

        - { path: ^/admin/newsfeed, roles: ROLE_NEWSFEED }
        - { path: ^/admin/timetable, roles: ROLE_TIMETABLE }
        - { path: ^/admin/user, roles: ROLE_USERS }

web_profiler:
  toolbar: true
  intercept_redirects: false
