imports:
  - { resource: parameters.yml }
  - { resource: services.yml }

framework:
    secret: '%secret%'
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/views/admin': admin

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  utf8mb4

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            main:
                is_bundle:  false
                type:       annotation
                dir:        '%kernel.project_dir%/src/Domain'
                prefix:     'PozytywneInicjatywy\Dashboard\Domain'
                alias:      Domain

web_profiler:
  toolbar: true
  intercept_redirects: false
