api.lucky:
  path: /lucky
  methods: [GET]
  defaults: { _controller: 'controller.api.lucky:fetch' }

api.timetable:
  path: /timetable/{class}
  methods: [GET]
  defaults: { _controller: 'controller.api.timetable:fetch' }

api.newsfeed:
  path: /newsfeed/{howMany}
  methods: [GET]
  defaults: { _controller: 'controller.api.newsfeed:fetch' }
