#
# Security
#
admin.security.login:
  path: /login
  methods: [GET]
  defaults: { _controller: 'controller.web.security:login' }

admin.security.loginCheck:
  path: /login
  methods: [POST]

admin.security.logout:
  path: /logout
  methods: [GET]

#
# Newsfeed
#
admin.newsfeed.home:
  path: /newsfeed
  methods: [GET]
  defaults: { _controller: 'controller.web.newsfeed:home' }

admin.newsfeed.new:
  path: /newsfeed/new
  methods: [GET]
  defaults: { _controller: 'controller.web.newsfeed:new' }

admin.newsfeed.newPost:
  path: /newsfeed
  methods: [POST]
  defaults: { _controller: 'controller.web.newsfeed:newPost' }

admin.newsfeed.edit:
  path: /newsfeed/{news}
  methods: [GET]
  defaults: { _controller: 'controller.web.newsfeed:edit' }

admin.newsfeed.editPost:
  path: /newsfeed/{news}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.newsfeed:editPost' }

admin.newsfeed.delete:
  path: /newsfeed/{news}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.newsfeed:delete' }

#
# Timetable
#
admin.timetable.home:
  path: /timetable
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:home' }

admin.timetable.class.list:
  path: /timetable/class
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:listClasses' }

admin.timetable.class.new:
  path: /timetable/class/new
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:newClass' }

admin.timetable.class.newPost:
  path: /timetable/class
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:newClassPost' }

admin.timetable.class.edit:
  path: /timetable/class/{class}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editClass' }

admin.timetable.class.editPost:
  path: /timetable/class/{class}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.timetable:editClassPost' }

admin.timetable.class.delete:
  path: /timetable/class/{class}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteClass' }

admin.timetable.subject.list:
  path: /timetable/subject
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:listSubjects' }

admin.timetable.subject.new:
  path: /timetable/subject/new
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:newSubject' }

admin.timetable.subject.newPost:
  path: /timetable/subject
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:newSubjectPost' }

admin.timetable.subject.edit:
  path: /timetable/subject/{subject}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editSubject' }

admin.timetable.subject.editPost:
  path: /timetable/subject/{subject}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.timetable:editSubjectPost' }

admin.timetable.subject.delete:
  path: /timetable/subject/{subject}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteSubject' }

admin.timetable.lessonHour.list:
  path: /timetable/lesson-hour
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:listLessonHour' }

admin.timetable.lessonHour.new:
  path: /timetable/lesson-hour/new
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:newLessonHour' }

admin.timetable.lessonHour.newPost:
  path: /timetable/lesson-hour
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:newLessonHourPost' }

admin.timetable.lessonHour.edit:
  path: /timetable/lesson-hour/{lessonHour}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editLessonHour' }

admin.timetable.lessonHour.editPost:
  path: /timetable/lesson-hour/{lessonHour}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.timetable:editLessonHourPost' }

admin.timetable.lessonHour.delete:
  path: /timetable/lesson-hour/{lessonHour}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteLessonHour' }

admin.timetable.editTimetable:
  path: /timetable/{class}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editTimetable' }

admin.timetable.saveLesson:
  path: /timetable/{class}/{day}/{lessonHour}
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:saveLesson' }

admin.timetable.deleteLesson:
  path: /timetable/{class}/{day}/{lessonHour}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteLesson' }

#
# User
#
admin.user.home:
  path: /user
  methods: [GET]
  defaults: { _controller: 'controller.web.user:home' }

admin.user.new:
  path: /user/new
  methods: [GET]
  defaults: { _controller: 'controller.web.user:new' }

admin.user.newPost:
  path: /user
  methods: [POST]
  defaults: { _controller: 'controller.web.user:newPost' }

admin.user.edit:
  path: /user/{user}
  methods: [GET]
  defaults: { _controller: 'controller.web.user:edit' }

admin.user.editPost:
  path: /user/{user}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.user:editPost' }

admin.user.delete:
  path: /user/{user}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.user:delete' }
