#
# Timetable
#
admin.timetable.home:
  path: /timetable
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:home' }

admin.timetable.class.list:
  path: /timetable/class
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:listClasses' }

admin.timetable.class.new:
  path: /timetable/class/new
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:newClass' }

admin.timetable.class.newPost:
  path: /timetable/class
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:newClassPost' }

admin.timetable.class.edit:
  path: /timetable/class/{class}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editClass' }

admin.timetable.class.editPost:
  path: /timetable/class/{class}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.timetable:editClassPost' }

admin.timetable.class.delete:
  path: /timetable/class/{class}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteClass' }

admin.timetable.subject.list:
  path: /timetable/subject
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:listSubjects' }

admin.timetable.subject.new:
  path: /timetable/subject/new
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:newSubject' }

admin.timetable.subject.newPost:
  path: /timetable/subject
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:newSubjectPost' }

admin.timetable.subject.edit:
  path: /timetable/subject/{subject}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editSubject' }

admin.timetable.subject.editPost:
  path: /timetable/subject/{subject}
  methods: [PATCH]
  defaults: { _controller: 'controller.web.timetable:editSubjectPost' }

admin.timetable.subject.delete:
  path: /timetable/subject/{subject}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteSubject' }

admin.timetable.editTimetable:
  path: /timetable/{class}
  methods: [GET]
  defaults: { _controller: 'controller.web.timetable:editTimetable' }

admin.timetable.saveLesson:
  path: /timetable/{class}/{day}/{lessonHour}
  methods: [POST]
  defaults: { _controller: 'controller.web.timetable:saveLesson' }

admin.timetable.deleteLesson:
  path: /timetable/{class}/{day}/{lessonHour}
  methods: [DELETE]
  defaults: { _controller: 'controller.web.timetable:deleteLesson' }
