services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    controller.api.lucky:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Api\LuckyController
        tags: ['controller.service_arguments']

    controller.api.timetable:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Api\TimetableController
        tags: ['controller.service_arguments']

    controller.api.newsfeed:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Api\NewsfeedController
        tags: ['controller.service_arguments']

    controller.web.security:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Web\SecurityController
        tags: ['controller.service_arguments']

    controller.web.timetable:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Web\TimetableController
        tags: ['controller.service_arguments']

    controller.web.newsfeed:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Web\NewsfeedController
        tags: ['controller.service_arguments']

    controller.web.user:
        class: PozytywneInicjatywy\Dashboard\UserInterface\Web\UserController
        tags: ['controller.service_arguments']

    #
    # Repositories
    #
    repository.schoolClass:
      class: PozytywneInicjatywy\Dashboard\Domain\SchoolClassRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\SchoolClass
      calls:
          - method: setLessonHourRepository
            arguments: ['@repository.lessonHour']

    repository.lessonHour:
      class: PozytywneInicjatywy\Dashboard\Domain\LessonHourRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\LessonHour

    repository.lesson:
      class: PozytywneInicjatywy\Dashboard\Domain\LessonRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\Lesson

    repository.subject:
      class: PozytywneInicjatywy\Dashboard\Domain\SubjectRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\Subject

    repository.news:
      class: PozytywneInicjatywy\Dashboard\Domain\NewsRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\News

    repository.user:
      class: PozytywneInicjatywy\Dashboard\Domain\UserRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
          - PozytywneInicjatywy\Dashboard\Domain\User

    #
    # Query handlers
    #
    queryHandler.fetchTimetable:
        class: PozytywneInicjatywy\Dashboard\Application\Query\Handler\FetchTimetableHandler

    #
    # Other
    #
    eventListener.cors:
        class: PozytywneInicjatywy\Dashboard\Symfony\EventListener\CorsListener
        tags:
          - { name: kernel.event_listener, event: kernel.response }
